### ISSUE TITLE
why not use the same method for both swal and izytoast

### ISSUE THREAD

**Issue by Masumrahmanhasan** [mhmiton/laravel-flashify#1]
it would be better to use the same method for both swal and izytoast 
it's really confusing when using different methods for two different flash message 

instead of doing different why not use this 

flashify()
    ->plugin('izytoast')
    ->title('Created')
    ->text('Data has been created successfully.')
    ->type('success')
    ->livewire($this);

**Comment by mhmiton** [comment]
@Masumrahmanhasan Thanks for your suggestions, maybe need to clarify the docs. I will do it later. But, you can use the same method for both plugins -

**For swal:**

```
flashify()
    ->plugin('swal')
    ->title('Created')
    ->text('Data has been created successfully.')
    ->type('success')
    ->livewire($this)
    ->fire();
```
**For izi-toast:**

```
flashify()
    ->plugin('izi-toast')
    ->title('Created')
    ->text('Data has been created successfully.')
    ->type('success')
    ->livewire($this)
    ->fire();
```

Note: You can use these methods or the array according to the docs. Both will work the same.
